sudo: required

services:
  - docker

cache:
  directories:
    - data_volumes
    - dist/flatpak/.flatpak-builder/cache
    - dist/flatpak/.flatpak-builder/ccache
    - dist/flatpak/.flatpak-builder/downloads
    - dist/flatpak/.flatpak-builder/git

arch:
  packages:
    - appstream-glib
  script:
    - ./util/travis-build.sh

before_script:
  - sudo add-apt-repository -y ppa:alexlarsson/flatpak
  - sudo apt-update -q
  - sudo apt-get install -y flatpak-builder

script:
  - ./util/arch-travis.sh
  - ./util/flatpak-travis.sh
